const data = {
  products: [
    {
      _id: "1",
      name: "Nike Slim Shirt",
      category: "Shirt",
      image: "/images/product-1.jpg",
      price: 120,
      countInStock: 20,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "2",
      name: "Adidas Fit Shirt",
      category: "Shirt",
      image: "/images/product-2.jpg",
      price: 100,
      countInStock: 8,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "3",
      name: "Lacoste Free Shirt",
      category: "Shirt",
      image: "/images/product-3.jpg",
      price: 220,
      countInStock: 7,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 17,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "Nike Slim Pants",
      category: "Pants",
      image: "/images/product-4.jpg",
      price: 78,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      _id: "5",
      name: "Puma Slim Pants",
      category: "Pants",
      image: "/images/product-5.jpg",
      price: 65,
      countInStock: 11,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "6",
      name: "Adidas Fit Pants",
      category: "Pants",
      image: "/images/product-6.jpg",
      price: 139,
      countInStock: 12,
      brand: "Adidas",
      rating: 4.5,
      numReview: 15,
      description: "high quality product",
    },
    {
      _id: "7",
      name: "White Elegant Suit",
      category: "PElegant Suit",
      image: "/images/product-15.jpg",
      price: 205,
      countInStock: 5,
      brand: "Golf",
      rating: 4.5,
      numReview: 22,
      description: "high quality product",
    },
    {
      _id: "31",
      name: "Black Dress for religious women",
      category: "Dress",
      image: "/images/product-31.jpg",
      price: 188,
      countInStock: 6,
      brand: "Turki",
      rating: 4.7,
      numReview: 28,
      description: "high quality product",
    },
    {
      _id: "32",
      name: "Dress for religious women",
      category: "Dress",
      image: "/images/product-32.jpg",
      price: 195,
      countInStock: 7,
      brand: "Turki",
      rating: 4.6,
      numReview: 23,
      description: "high quality product",
    },
    {
      _id: "33",
      name: "Golden Woman's veil",
      category: "Veil",
      image: "/images/product-33.jpg",
      price: 35,
      countInStock: 22,
      brand: "Turki",
      rating: 4.2,
      numReview: 28,
      description: "high quality product",
    },
    {
      _id: "34",
      name: "Brown Woman's veil",
      category: "Veil",
      image: "/images/product-34.jpg",
      price: 36,
      countInStock: 25,
      brand: "Turki",
      rating: 4.3,
      numReview: 32,
      description: "high quality product",
    },
    {
      _id: "16",
      name: "Blue Elegant Suit",
      category: "Elegant Suit",
      image: "/images/product-16.jpg",
      price: 210,
      countInStock: 14,
      brand: "Golf",
      rating: 4.5,
      numReview: 27,
      description: "high quality product",
    },
    {
      _id: "17",
      name: "Women's sports suit",
      category: "Sports Suit",
      image: "/images/product-17.jpg",
      price: 199,
      countInStock: 2,
      brand: "Adidas",
      rating: 4.7,
      numReview: 50,
      description: "high quality product",
    },
    {
      _id: "18",
      name: "Day dress",
      category: "dRESS",
      image: "/images/product-18.jpg",
      price: 132,
      countInStock: 17,
      brand: "T&E",
      rating: 4.0,
      numReview: 19,
      description: "high quality product",
    },
    {
      _id: "19",
      name: "Evening dress",
      category: "Dress",
      image: "/images/product-19.jpg",
      price: 280,
      countInStock: 3,
      brand: "T&E",
      rating: 4.6,
      numReview: 26,
      description: "high quality product",
    },
    {
      _id: "21",
      name: "Evening dress",
      category: "Dress",
      image: "/images/product-21.jpg",
      price: 300,
      countInStock: 4,
      brand: "T&E",
      rating: 4.8,
      numReview: 45,
      description: "high quality product",
    },
    {
      _id: "25",
      name: "Sport Bra",
      category: "Bra",
      image: "/images/product-25.jpg",
      price: 125,
      countInStock: 30,
      brand: "Adidas",
      rating: 4.2,
      numReview: 19,
      description: "high quality product",
    },
    {
      _id: "26",
      name: "Saint Laurent Bra",
      category: "Bra",
      image: "/images/product-26.jpg",
      price: 215,
      countInStock: 27,
      brand: "Saint Laurent",
      rating: 4.9,
      numReview: 35,
      description: "high quality product",
    },
    {
      _id: "27",
      name: "Italian translation of 'bra",
      category: "Bra",
      image: "/images/product-27.jpg",
      price: 185,
      countInStock: 16,
      brand: "Reggiseno",
      rating: 4.2,
      numReview: 20,
      description: "high quality product",
    },
    {
      _id: "28",
      name: "Push Up Bra",
      category: "Bra",
      image: "/images/product-28.jpg",
      price: 200,
      countInStock: 0,
      brand: "Victoria's Secret",
      rating: 4.7,
      numReview: 19,
      description: "high quality product",
    },
  ],
};

export default data ;